DROP TABLE IF EXISTS choices CASCADE;
CREATE TABLE choices (
  id SERIAL PRIMARY KEY NOT NULL,
  option TEXT NOT NULL,
  score INTEGER NOT NULL,
  poll_id INTEGER REFERENCES polls(id) ON DELETE CASCADE
);
