DROP TABLE IF EXISTS voters CASCADE;
CREATE TABLE voters (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  poll_id INTEGER REFERENCES polls(id) ON DELETE CASCADE,
  ip_address VARCHAR(255) NOT NULL
);
